server:
  error:
    include-message: always
  port: 4001
spring:
  application:
    name: TIH
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/tih?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:david1311}

    # this is to connect remote db on local but when deploying leave it commented
#    url: jdbc:mysql://161.35.71.73:${DB_PORT:3307}/tih?createDatabaseIfNotExist=true
#    username: ${DB_USERNAME:root}
#    password: ${DB_PASSWORD:gen123}

  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-circular-references: true


